import React, { useState, useEffect } from 'react'

import { Loader, Card, FormField } from '../components';

const Home = () => {
  const [loading, setloading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);



  return (
    <section className='max-w7xl mx-auto'>
        <div>
            <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
            <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E</p>
        </div>
        
        <div className="mt-16">
            <FormField />
        </div>

        <div className="mt-10">
            {loading ? (
                <div className='flex justify-center items-center'>
                    <Loader />
                    {/* if loading is true then this will be executed, the svg file for loading */}
                </div>
            ) : (
                <>
                 
                </>
            )}
        </div>
    </section>
  )
}

export default Home